version: '3.5'

x-volumes:
  - &app-src ${APP_PATH_HOST}:${APP_PATH_CONTAINER}

services:

  nginx:
    image: nginx:alpine
    container_name: yii2-docker_nginx
    working_dir: ${APP_PATH_CONTAINER}
    networks:
      - yii2-docker_net
    ports:
      - 80:80
    volumes:
      - *app-src
      - ./docker/services/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro

  php-fpm:
    image: yii2-docker_php-fpm:v1.0.0
    build:
      context: docker/services/php-fpm/
      dockerfile: Alpine.Dockerfile
    container_name: yii2-docker_php-fpm
    working_dir: ${APP_PATH_CONTAINER}
    networks:
      - yii2-docker_net
    volumes:
      - *app-src
      - composer-cache:/var/www/.composer


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: test
      MYSQL_USER: test
    ports:
      - 3310:3306
    networks:
      - yii2-docker_net
    volumes:
      - db-volume:/var/lib/mysql

networks:
  yii2-docker_net:
    name: yii2-docker_network

volumes:
  composer-cache:
    name: yii2-docker_composer_cache
  db-volume:
    name: yii2-docker_db_volume